resolver: lts-14.27
local-bin-path: bin
extra-deps:
- ref-fd-0.4.0.2
- git: https://github.com/mainland/fixed-q.git
  commit: 2e7bfef593b1fc81179b0c4e414bf20cf552c676
- git: https://github.com/mainland/language-vhdl-quote.git
  commit: bdb5df7c609070da61cc417ca38f7d6a142e5355
