resolver: lts-14.27
local-bin-path: bin
extra-deps:
- hgmp-0.1.1
- long-double-0.1.1
- ref-fd-0.4.0.2
- rounded-1.1
- git: https://github.com/mainland/fixed-q.git
  commit: 84c77f8adc018b9262c9a7369a56ca646ecc2031
- git: https://github.com/mainland/language-vhdl-quote.git
  commit: d35e0accec7cead0dbf698274466c272f37fca64
